// <auto-generated>
// This file is generated by SceneEnumGenerator.
// Do not edit manually.
// </auto-generated>

public enum SceneId
{
    None = -1,
    MainMenu,
    Gameplay
}

public static class SceneIdExtensions
{
    public static string AsString(this SceneId scene)
    {
        return scene switch
        {
            SceneId.MainMenu => "MainMenu",
            SceneId.Gameplay => "Gameplay",
            _ => string.Empty
        };
    }
}
