// <auto-generated>
// This file is generated by TagEnumGenerator.
// Do not edit manually.
// </auto-generated>

using UnityEngine;

public enum TagId
{
    None = -1,
    Untagged,
    Respawn,
    Finish,
    EditorOnly,
    MainCamera,
    Player,
    GameController,
    Enemy,
    PlayerProjectile
}

public static class TagIdExtensions
{
    public static string AsString(this TagId tag)
    {
        return tag switch
        {
            TagId.Untagged => "Untagged",
            TagId.Respawn => "Respawn",
            TagId.Finish => "Finish",
            TagId.EditorOnly => "EditorOnly",
            TagId.MainCamera => "MainCamera",
            TagId.Player => "Player",
            TagId.GameController => "GameController",
            TagId.Enemy => "Enemy",
            TagId.PlayerProjectile => "PlayerProjectile",
            _ => string.Empty
        };
    }

    public static bool Matches(this GameObject gameObject, TagId tag)
    {
        return gameObject != null && gameObject.CompareTag(tag.AsString());
    }
}
