using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

/// <summary>
/// Generates a strongly-typed enum from scenes listed in Build Settings.
/// Regenerates when EditorBuildSettings scenes are modified.
/// </summary>
[InitializeOnLoad]
public static class SceneEnumGenerator
{
    private const string OutputPath = "Assets/__generated__/SceneId.cs";
    private const string LastScenesHashKey = "SceneEnumGenerator.LastScenesHash";

    static SceneEnumGenerator()
    {
        // Defer generation until editor is fully initialized.
        EditorApplication.delayCall += GenerateIfChanged;
        EditorBuildSettings.sceneListChanged += GenerateIfChanged;
    }

    [MenuItem("Tools/Code Generation/Generate Scene Enum")]
    public static void GenerateNow()
    {
        GenerateAndWrite(force: true);
    }

    internal static void GenerateIfChanged()
    {
        GenerateAndWrite(force: false);
    }

    private static void GenerateAndWrite(bool force)
    {
        EditorBuildSettingsScene[] scenes = EditorBuildSettings.scenes;
        string hash = ComputeScenesHash(scenes);

        if (!force)
        {
            string lastHash = EditorPrefs.GetString(LastScenesHashKey, string.Empty);
            if (string.Equals(hash, lastHash, StringComparison.Ordinal))
            {
                return;
            }
        }

        string content = BuildEnumFileContent(scenes);

        string directory = Path.GetDirectoryName(OutputPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        bool needsWrite = true;
        if (File.Exists(OutputPath))
        {
            string existing = File.ReadAllText(OutputPath);
            needsWrite = !string.Equals(existing, content, StringComparison.Ordinal);
        }

        if (needsWrite)
        {
            File.WriteAllText(OutputPath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            AssetDatabase.ImportAsset(OutputPath);
            UnityEngine.Debug.Log($"[SceneEnumGenerator] Generated {OutputPath}");
        }

        EditorPrefs.SetString(LastScenesHashKey, hash);
    }

    private static string BuildEnumFileContent(IReadOnlyList<EditorBuildSettingsScene> scenes)
    {
        StringBuilder sb = new StringBuilder();
        List<(string EnumName, string SceneName)> members = BuildUniqueMembers(scenes);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by SceneEnumGenerator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("public enum SceneId");
        sb.AppendLine("{");
        sb.AppendLine("    None = -1,");

        for (int i = 0; i < members.Count; i++)
        {
            string comma = i < members.Count - 1 ? "," : string.Empty;
            sb.AppendLine($"    {members[i].EnumName}{comma}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public static class SceneIdExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static string AsString(this SceneId scene)");
        sb.AppendLine("    {");
        sb.AppendLine("        return scene switch");
        sb.AppendLine("        {");

        for (int i = 0; i < members.Count; i++)
        {
            sb.AppendLine($"            SceneId.{members[i].EnumName} => \"{EscapeForStringLiteral(members[i].SceneName)}\",");
        }

        sb.AppendLine("            _ => string.Empty");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<(string EnumName, string SceneName)> BuildUniqueMembers(IReadOnlyList<EditorBuildSettingsScene> scenes)
    {
        HashSet<string> usedNames = new HashSet<string>(StringComparer.Ordinal);
        List<(string EnumName, string SceneName)> members = new List<(string EnumName, string SceneName)>();

        for (int i = 0; i < scenes.Count; i++)
        {
            EditorBuildSettingsScene scene = scenes[i];
            if (scene == null || !scene.enabled || string.IsNullOrWhiteSpace(scene.path))
            {
                continue;
            }

            string sceneName = Path.GetFileNameWithoutExtension(scene.path);
            if (string.IsNullOrWhiteSpace(sceneName))
            {
                continue;
            }

            string enumName = ToPascalIdentifier(sceneName);
            string baseName = enumName;
            int suffix = 2;

            while (!usedNames.Add(enumName))
            {
                enumName = $"{baseName}_{suffix}";
                suffix++;
            }

            members.Add((enumName, sceneName));
        }

        return members;
    }

    private static string ToPascalIdentifier(string value)
    {
        StringBuilder sb = new StringBuilder(value.Length);
        bool uppercaseNext = true;

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];

            if (char.IsLetterOrDigit(c))
            {
                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(uppercaseNext ? char.ToUpperInvariant(c) : c);
                uppercaseNext = false;
            }
            else
            {
                uppercaseNext = true;
            }
        }

        if (sb.Length == 0)
        {
            return "Scene";
        }

        string identifier = sb.ToString();
        if (IsCSharpKeyword(identifier))
        {
            return $"_{identifier}";
        }

        return identifier;
    }

    private static bool IsCSharpKeyword(string identifier)
    {
        switch (identifier)
        {
            case "Abstract":
            case "As":
            case "Base":
            case "Bool":
            case "Break":
            case "Byte":
            case "Case":
            case "Catch":
            case "Char":
            case "Checked":
            case "Class":
            case "Const":
            case "Continue":
            case "Decimal":
            case "Default":
            case "Delegate":
            case "Do":
            case "Double":
            case "Else":
            case "Enum":
            case "Event":
            case "Explicit":
            case "Extern":
            case "False":
            case "Finally":
            case "Fixed":
            case "Float":
            case "For":
            case "Foreach":
            case "Goto":
            case "If":
            case "Implicit":
            case "In":
            case "Int":
            case "Interface":
            case "Internal":
            case "Is":
            case "Lock":
            case "Long":
            case "Namespace":
            case "New":
            case "Null":
            case "Object":
            case "Operator":
            case "Out":
            case "Override":
            case "Params":
            case "Private":
            case "Protected":
            case "Public":
            case "Readonly":
            case "Ref":
            case "Return":
            case "Sbyte":
            case "Sealed":
            case "Short":
            case "Sizeof":
            case "Stackalloc":
            case "Static":
            case "String":
            case "Struct":
            case "Switch":
            case "This":
            case "Throw":
            case "True":
            case "Try":
            case "Typeof":
            case "Uint":
            case "Ulong":
            case "Unchecked":
            case "Unsafe":
            case "Ushort":
            case "Using":
            case "Virtual":
            case "Void":
            case "Volatile":
            case "While":
                return true;
            default:
                return false;
        }
    }

    private static string ComputeScenesHash(IReadOnlyList<EditorBuildSettingsScene> scenes)
    {
        unchecked
        {
            int hash = 17;
            for (int i = 0; i < scenes.Count; i++)
            {
                EditorBuildSettingsScene scene = scenes[i];
                hash = (hash * 31) + (scene?.path?.GetHashCode() ?? 0);
                hash = (hash * 31) + (scene != null && scene.enabled ? 1 : 0);
            }

            return hash.ToString();
        }
    }

    private static string EscapeForStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}

internal sealed class EditorBuildSettingsPostprocessor : AssetPostprocessor
{
    private const string EditorBuildSettingsPath = "ProjectSettings/EditorBuildSettings.asset";

    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths)
    {
        if (ContainsEditorBuildSettingsPath(importedAssets) ||
            ContainsEditorBuildSettingsPath(deletedAssets) ||
            ContainsEditorBuildSettingsPath(movedAssets) ||
            ContainsEditorBuildSettingsPath(movedFromAssetPaths))
        {
            SceneEnumGenerator.GenerateIfChanged();
        }
    }

    private static bool ContainsEditorBuildSettingsPath(string[] paths)
    {
        if (paths == null)
        {
            return false;
        }

        for (int i = 0; i < paths.Length; i++)
        {
            if (string.Equals(paths[i], EditorBuildSettingsPath, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}