using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;

/// <summary>
/// Generates a strongly-typed enum from Unity tags.
/// Regenerates when tags are modified in TagManager.
/// </summary>
[InitializeOnLoad]
public static class TagEnumGenerator
{
    private const string OutputPath = "Assets/__generated__/TagId.cs";
    private const string LastTagsHashKey = "TagEnumGenerator.LastTagsHash";

    static TagEnumGenerator()
    {
        // Defer generation until editor is fully initialized.
        EditorApplication.delayCall += GenerateIfChanged;
    }

    [MenuItem("Tools/Code Generation/Generate Tag Enum")]
    public static void GenerateNow()
    {
        GenerateAndWrite(force: true);
    }

    internal static void GenerateIfChanged()
    {
        GenerateAndWrite(force: false);
    }

    private static void GenerateAndWrite(bool force)
    {
        string[] tags = InternalEditorUtility.tags;
        string hash = ComputeTagsHash(tags);

        if (!force)
        {
            string lastHash = EditorPrefs.GetString(LastTagsHashKey, string.Empty);
            if (string.Equals(hash, lastHash, StringComparison.Ordinal))
            {
                return;
            }
        }

        string content = BuildEnumFileContent(tags);

        string directory = Path.GetDirectoryName(OutputPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        bool needsWrite = true;
        if (File.Exists(OutputPath))
        {
            string existing = File.ReadAllText(OutputPath);
            needsWrite = !string.Equals(existing, content, StringComparison.Ordinal);
        }

        if (needsWrite)
        {
            File.WriteAllText(OutputPath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            AssetDatabase.ImportAsset(OutputPath);
            Debug.Log($"[TagEnumGenerator] Generated {OutputPath}");
        }

        EditorPrefs.SetString(LastTagsHashKey, hash);
    }

    private static string BuildEnumFileContent(IReadOnlyList<string> tags)
    {
        StringBuilder sb = new StringBuilder();
        List<(string EnumName, string TagValue)> members = BuildUniqueMembers(tags);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by TagEnumGenerator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public enum TagId");
        sb.AppendLine("{");
        sb.AppendLine("    None = -1,");

        for (int i = 0; i < members.Count; i++)
        {
            string comma = i < members.Count - 1 ? "," : string.Empty;
            sb.AppendLine($"    {members[i].EnumName}{comma}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public static class TagIdExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static string AsString(this TagId tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return tag switch");
        sb.AppendLine("        {");

        for (int i = 0; i < members.Count; i++)
        {
            sb.AppendLine($"            TagId.{members[i].EnumName} => \"{EscapeForStringLiteral(members[i].TagValue)}\",");
        }

        sb.AppendLine("            _ => string.Empty");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool Matches(this GameObject gameObject, TagId tag)");
        sb.AppendLine("    {");
        sb.AppendLine("        return gameObject != null && gameObject.CompareTag(tag.AsString());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<(string EnumName, string TagValue)> BuildUniqueMembers(IReadOnlyList<string> tags)
    {
        HashSet<string> usedNames = new HashSet<string>(StringComparer.Ordinal);
        List<(string EnumName, string TagValue)> members = new List<(string EnumName, string TagValue)>();

        for (int i = 0; i < tags.Count; i++)
        {
            string tag = tags[i];
            if (string.IsNullOrWhiteSpace(tag))
            {
                continue;
            }

            string enumName = ToPascalIdentifier(tag);
            string baseName = enumName;
            int suffix = 2;

            while (!usedNames.Add(enumName))
            {
                enumName = $"{baseName}_{suffix}";
                suffix++;
            }

            members.Add((enumName, tag));
        }

        return members;
    }

    private static string ToPascalIdentifier(string value)
    {
        StringBuilder sb = new StringBuilder(value.Length);
        bool uppercaseNext = true;

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];

            if (char.IsLetterOrDigit(c))
            {
                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(uppercaseNext ? char.ToUpperInvariant(c) : c);
                uppercaseNext = false;
            }
            else
            {
                uppercaseNext = true;
            }
        }

        if (sb.Length == 0)
        {
            return "Tag";
        }

        string identifier = sb.ToString();
        if (IsCSharpKeyword(identifier))
        {
            return $"_{identifier}";
        }

        return identifier;
    }

    private static bool IsCSharpKeyword(string identifier)
    {
        switch (identifier)
        {
            case "Abstract":
            case "As":
            case "Base":
            case "Bool":
            case "Break":
            case "Byte":
            case "Case":
            case "Catch":
            case "Char":
            case "Checked":
            case "Class":
            case "Const":
            case "Continue":
            case "Decimal":
            case "Default":
            case "Delegate":
            case "Do":
            case "Double":
            case "Else":
            case "Enum":
            case "Event":
            case "Explicit":
            case "Extern":
            case "False":
            case "Finally":
            case "Fixed":
            case "Float":
            case "For":
            case "Foreach":
            case "Goto":
            case "If":
            case "Implicit":
            case "In":
            case "Int":
            case "Interface":
            case "Internal":
            case "Is":
            case "Lock":
            case "Long":
            case "Namespace":
            case "New":
            case "Null":
            case "Object":
            case "Operator":
            case "Out":
            case "Override":
            case "Params":
            case "Private":
            case "Protected":
            case "Public":
            case "Readonly":
            case "Ref":
            case "Return":
            case "Sbyte":
            case "Sealed":
            case "Short":
            case "Sizeof":
            case "Stackalloc":
            case "Static":
            case "String":
            case "Struct":
            case "Switch":
            case "This":
            case "Throw":
            case "True":
            case "Try":
            case "Typeof":
            case "Uint":
            case "Ulong":
            case "Unchecked":
            case "Unsafe":
            case "Ushort":
            case "Using":
            case "Virtual":
            case "Void":
            case "Volatile":
            case "While":
                return true;
            default:
                return false;
        }
    }

    private static string ComputeTagsHash(IReadOnlyList<string> tags)
    {
        unchecked
        {
            int hash = 17;
            for (int i = 0; i < tags.Count; i++)
            {
                hash = (hash * 31) + (tags[i]?.GetHashCode() ?? 0);
            }
            return hash.ToString();
        }
    }

    private static string EscapeForStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}

internal sealed class TagManagerPostprocessor : AssetPostprocessor
{
    private const string TagManagerPath = "ProjectSettings/TagManager.asset";

    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths)
    {
        if (ContainsTagManagerPath(importedAssets) ||
            ContainsTagManagerPath(deletedAssets) ||
            ContainsTagManagerPath(movedAssets) ||
            ContainsTagManagerPath(movedFromAssetPaths))
        {
            TagEnumGenerator.GenerateIfChanged();
        }
    }

    private static bool ContainsTagManagerPath(string[] paths)
    {
        if (paths == null)
        {
            return false;
        }

        for (int i = 0; i < paths.Length; i++)
        {
            if (string.Equals(paths[i], TagManagerPath, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}